name: Makefile Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run Makefile Install
      run: |
        make install

    - name: Run Makefile Process Data
      run: |
        make process_data

    - name: Run Makefile Run Model
      run: |
        make run_model

    - name: Run Makefile Run Website
      run: |
        make run_website &
      # Adding a sleep delay to simulate a website being run during testing
      # This can be removed if actual website interaction testing is added sleep 30

    - name: Clean Up
      run: |
        make clean
